debug: true
server:
  port: 8765
  ssl:
    key-store: classpath:server.jks
    key-store-password: password
    key-password: password
    
spring:
  aop:
    proxy-target-class: true
  redis:
    host: localhost
    port: 6379
    default_expire_time: 86400

zuul:
  routes:
    authserver:
      path: /authserver/**
      url: http://localhost:9999
    user:
      path: /user/**
      url: http://localhost:8080/authserver/uaa/user
    frontend1:
      path: /ui/**
      serviceId: webui
      stripPrefix: false
    frontend2:
      path: /webui/**
      serviceId: webui

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

hystrix:
  command:
    frontend:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000

management:
  security:
    enabled: false
security:
  basic:
    enabled: false
  user:
    password: none
  oauth2:
    client:
      accessTokenUri: http://localhost:8080/authserver/uaa/oauth/token
      userAuthorizationUri: http://localhost:8080/authserver/uaa/oauth/authorize
      clientId: acme
      clientSecret: acmesecret
    resource:
      jwt:
        id: openid
        keyValue: |
          -----BEGIN PUBLIC KEY-----
          MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAnGp/Q5lh0P8nPL21oMMrt2RrkT9AW5jgYwLfSUnJVc9G6uR3cXRRDCjHqWU5WYwivcF180A6CWp/ireQFFBNowgc5XaA0kPpzEtgsA5YsNX7iSnUibB004iBTfU9hZ2Rbsc8cWqynT0RyN4TP1RYVSeVKvMQk4GT1r7JCEC+TNu1ELmbNwMQyzKjsfBXyIOCFU/E94ktvsTZUHF4Oq44DBylCDsS1k7/sfZC2G5EU7Oz0mhG8+Uz6MSEQHtoIi6mc8u64Rwi3Z3tscuWG2ShtsUFuNSAFNkY7LkLn+/hxLCu2bNISMaESa8dG22CIMuIeRLVcAmEWEWH5EEforTg+QIDAQAB
          -----END PUBLIC KEY-----

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG
    com.netflix.discovery: 'OFF'

---
# For deployment in Docker containers
spring:
  profiles: docker

eureka:
  instance:
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://discovery:8761/eureka/
