
---
spring:
  profiles:
    name: cloud
    
server:
  port: 8000

ribbon:
  ServerListRefreshInterval: 1000

endpoints:
  health:
    sensitive: false
  restart:
    enabled: true
  shutdown:
    enabled: true

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://pro-discovery:8761/eureka/

spring.cloud.config.discovery.enabled: true

---
spring:
  profiles:
    name: development
    
server:
  port: 8000

ribbon:
  ServerListRefreshInterval: 1000

endpoints:
  health:
    sensitive: false
  restart:
    enabled: true
  shutdown:
    enabled: true

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://discovery:8761/eureka/

spring.cloud.config.discovery.enabled: true