
---
spring:
  profiles: cloud
server:
  port: 10000
endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
  health:
    sensitive: false
eureka:
  instance:
    hostname: pro-gateway
    nonSecurePort: 80
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://pro-discovery:8761/eureka/

---
spring:
  profiles: development
server:
  port: 10000
endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
  health:
    sensitive: false
eureka:
  instance:
    preferIpAddress: true
    #hostname: gateway
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://discovery:8761/eureka/
      
ribbon:
  eureka:
    enabled: true
    
zuul:
  routes:
    members: 
      path:/members/**
      serviceId:members
    webui:
      path: /**
      serviceId: webui
 #   vaadin:   vaadinServlet
 ##     path: /vaadinServlet/**
  #    serviceId: webui
  #  vaadin2:
 #     path: /UIDL/**
  #    serviceId: webui
      
   # webui: /webui/**
  #  webui: /VAADIN/**
    
logging:
  level:
    ROOT: WARN
    org.springframework.web: DEBUG
    # Set DEBUG level on Hystrix to get an error message when a fallback method is used.
    com.netflix.hystrix: DEBUG